### ISSUE TITLE
add content to grammars/

### ISSUE THREAD

**Issue by vanhauser-thc** [OMH4ck/PolyGlot#49]
the examples/php/Dockerfile shows that there should be php grammar and seeds, but they are missing from the repository.
could you please add them (and maybe others you have)?

**Comment by Changochen** [comment]
I think they should be in the submodule (https://github.com/OMH4ck/PolyGlot-Grammar/tree/d857be160063f330f197e92ea9308577eb61b95a)? Please let me know if you have any other problem.
