### ISSUE TITLE
How to refactor source code via IR？

### ISSUE THREAD

**Issue by HopeDevote** [OMH4ck/PolyGlot#51]
Hello, author
        I want to know how to perform inorder traversal on the IR program to reconstruct the original source program? Where is the corresponding code？

**Comment by Changochen** [comment]
https://github.com/OMH4ck/PolyGlot/blob/7162dbc78f24ee3cc6ed019ef42a0cd913815e47/srcs/internal/srcs/ir.cpp#L119

**Comment by HopeDevote** [comment]
您好，您的文件我已收到！
